# Generated by Django 3.2.12 on 2022-12-06 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='commentss',
            table='Commentss',
        ),
    ]
