# Generated by Django 3.2.12 on 2022-12-06 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_alter_commentss_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='commentss',
            table='Comments',
        ),
    ]
