# Generated by Django 3.2.12 on 2022-11-28 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='genre',
            field=models.CharField(choices=[('추리', '추리'), ('스릴러', '스릴러'), ('공포', '공포'), ('판타지', '판타지'), ('로맨스', '로맨스')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='matching',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='time',
            field=models.CharField(choices=[('오전', '06:00 ~ 11:59'), ('오후', '12:00 ~ 17:59'), ('저녁', '18:00 ~ 23:59')], max_length=20, null=True),
        ),
    ]
