# Generated by Django 3.2.12 on 2022-11-28 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='day',
            field=models.CharField(choices=[('월', '월요일'), ('화', '화요일'), ('수', '수요일'), ('목', '목요일'), ('금', '금요일')], max_length=20, null=True),
        ),
    ]
