# Generated by Django 3.2.12 on 2022-11-28 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20221128_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='time',
            field=models.CharField(choices=[('오전', '오전 : 06:00 ~ 11:59 사이'), ('오후', '오후 : 12:00 ~ 17:59 사이'), ('저녁', '저녁 : 18:00 ~ 23:59 사이')], default='시간', max_length=20),
        ),
    ]
