# Generated by Django 3.2.12 on 2022-11-28 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20221128_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='day',
            field=models.CharField(default='요일', max_length=20),
        ),
    ]
