# Generated by Django 3.2.12 on 2022-11-28 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_user_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='genre',
            field=models.CharField(default='장르', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='time',
            field=models.CharField(default='시간', max_length=20),
        ),
    ]
