# Generated by Django 3.2.12 on 2022-11-28 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20221128_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='day',
            field=models.CharField(choices=[('요일', '요일'), ('월', '월요일'), ('화', '화요일'), ('수', '수요일'), ('목', '목요일'), ('금', '금요일'), ('토', '토요일'), ('일', '일요일')], default='요일', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='genre',
            field=models.CharField(choices=[('장르', '장르'), ('추리', '추리'), ('스릴러', '스릴러'), ('공포', '공포'), ('판타지', '판타지'), ('로맨스', '로맨스')], default='장르', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='time',
            field=models.CharField(choices=[('시간', '시간'), ('오전', '오전 : 06:00 ~ 11:59 사이'), ('오후', '오후 : 12:00 ~ 17:59 사이'), ('저녁', '저녁 : 18:00 ~ 23:59 사이')], default='시간', max_length=20),
        ),
    ]
