# Generated by Django 3.2.12 on 2022-12-01 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_profile_ages'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ages',
            field=models.CharField(choices=[('선택해주세요', '선택해주세요'), ('20대', '20대'), ('30대', '30대'), ('40대', '40대'), ('50대', '50대')], default='선택해주세요', max_length=20),
        ),
    ]
