# Generated by Django 3.2.12 on 2022-12-01 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20221201_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='intro',
            field=models.TextField(blank=True, null=True),
        ),
    ]
