# Generated by Django 3.2.12 on 2022-12-06 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20221202_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='daytime',
            field=models.TextField(blank=True),
        ),
    ]
