# Generated by Django 3.2.12 on 2022-12-08 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_remove_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ages',
            field=models.CharField(blank=True, choices=[('선택해주세요', '선택해주세요'), ('20대', '20대'), ('30대', '30대'), ('40대', '40대'), ('50대', '50대')], default='선택해주세요', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='day',
            field=models.CharField(blank=True, choices=[('요일', '요일'), ('월', '월요일'), ('화', '화요일'), ('수', '수요일'), ('목', '목요일'), ('금', '금요일'), ('토', '토요일'), ('일', '일요일')], default='요일', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='genre',
            field=models.CharField(blank=True, choices=[('장르', '장르'), ('추리', '추리'), ('스릴러', '스릴러'), ('공포', '공포'), ('판타지', '판타지'), ('로맨스', '로맨스')], default='장르', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='time',
            field=models.CharField(blank=True, choices=[('시간', '시간'), ('오전', '오전 : 06:00 ~ 11:59 사이'), ('오후', '오후 : 12:00 ~ 17:59 사이'), ('저녁', '저녁 : 18:00 ~ 23:59 사이')], default='시간', max_length=20),
        ),
    ]
