# Generated by Django 3.2.12 on 2022-12-08 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20221207_1539'),
        ('accounts', '0027_auto_20221209_0021'),
    ]

    operations = [
    ]
