# Generated by Django 3.2.12 on 2022-12-08 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_merge_0024_auto_20221207_1539_0027_auto_20221209_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='daytime',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
        ),
    ]
