# Generated by Django 3.2.12 on 2022-12-03 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='garbage',
            new_name='trash_can',
        ),
    ]
