# Generated by Django 3.2.12 on 2022-12-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_rename_garbage_notes_trash_can'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='to_id',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
