# Generated by Django 3.2.12 on 2022-12-02 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0007_alter_review_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='genre',
            field=models.CharField(choices=[('장르를 선택해주세요', '장르를 선택해주세요'), ('추리', '추리'), ('스릴러', '스릴러'), ('공포', '공포'), ('판타지', '판타지'), ('로맨스', '로맨스')], default='장르를 선택해주세요', max_length=20, null=True),
        ),
    ]
