# Generated by Django 3.2.12 on 2022-12-10 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_alter_book_genre'),
        ('review', '0020_alter_review_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='book_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.image'),
        ),
    ]
