# Generated by Django 3.2.12 on 2022-12-12 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0022_remove_review_genre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
