# Generated by Django 3.2.12 on 2022-12-14 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0023_delete_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='tags',
        ),
    ]
