# Generated by Django 3.2.12 on 2022-12-07 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book_genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField()),
                ('summary', models.TextField(max_length=500)),
                ('matching_count', models.PositiveIntegerField()),
                ('genre', models.ForeignKey(blank=True, max_length=10, on_delete=django.db.models.deletion.PROTECT, to='book.book_genre')),
            ],
        ),
    ]
