# Generated by Django 3.2.12 on 2022-12-08 08:32

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='book_image/'),
        ),
    ]
