# Generated by Django 3.2.12 on 2022-12-09 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20221209_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='book_genre',
        ),
    ]
