# Generated by Django 3.2.12 on 2022-12-09 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20221209_1027'),
        ('book', '0004_auto_20221209_1233'),
    ]

    operations = [
    ]
