# Generated by Django 3.2.12 on 2022-12-09 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_auto_20221209_1512'),
    ]

    operations = [
        migrations.DeleteModel(
            name='book_genre',
        ),
    ]
