# Generated by Django 3.2.12 on 2022-12-09 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_alter_book_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
