# Generated by Django 3.2.12 on 2022-12-09 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_delete_book_genre'),
        ('book', '0008_alter_book_genre'),
    ]

    operations = [
    ]
