# Generated by Django 3.2.12 on 2022-12-12 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_alter_book_genre'),
        ('book', '0011_alter_book_matching_count'),
    ]

    operations = [
    ]
