# Generated by Django 3.2.12 on 2022-12-12 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_merge_20221212_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(blank=True, choices=[('추리', '추리'), ('스릴러', '스릴러'), ('공포', '공포'), ('판타지', '판타지'), ('로맨스', '로맨스')], max_length=20, null=True),
        ),
    ]
