# Generated by Django 3.2.12 on 2022-12-12 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_merge_20221212_1646'),
        ('book', '0014_alter_image_image'),
    ]

    operations = [
    ]
