# Generated by Django 3.2.12 on 2022-12-13 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0019_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(blank=True, choices=[('1', '공포/추리'), ('2', '판타지'), ('3', '로맨스/가족'), ('4', '역사/철학'), ('5', '정치/경제')], max_length=20, null=True),
        ),
    ]
