# Generated by Django 3.2.12 on 2022-12-13 06:33

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0029_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to='images/'),
        ),
    ]
