# Generated by Django 3.2.12 on 2022-12-13 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0037_alter_book_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(blank=True, choices=[('공포/추리', '공포/추리'), ('판타지', '판타지'), ('로맨스/가족', '로맨스/가족'), ('역사/철학', '역사/철학'), ('정치/경제', '정치/경제')], max_length=20, null=True),
        ),
    ]
