# Generated by Django 3.2.12 on 2022-12-13 16:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0038_alter_book_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(blank=True, choices=[('1', '공포/추리'), ('2', '판타지'), ('3', '로맨스/가족'), ('4', '역사/철학'), ('5', '정치/경제')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='grade',
            field=models.FloatField(default=1, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
