# Generated by Django 3.2.12 on 2022-12-14 06:12

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('book', '0040_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(blank=True, choices=[('1', '공포/추리'), ('2', '판타지/무협'), ('3', '로맨스/가족'), ('4', '역사/철학'), ('5', '정치/경제')], max_length=20, null=True),
        ),
    ]
